## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [14]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

print(vendas)

[[50 60 70 65 80]
 [85 90 78 92 88]
 [72 75 68 77 76]]


In [15]:
#vendas totais

vendas_totais = np.reshape(vendas, (3, -1))
vendas_produto = vendas_totais.sum(axis=1)

print(f'vendas totais de cada produto: {vendas_produto}')

for i in range(3):
    print(f'vendas do produto {i+1}: {vendas_produto[i]}')
#print(f'vendas do produto A: {vendas_produto[0]}')
#print(f'vendas do produto B: {vendas_produto[1]}')
#print(f'vendas do produto C: {vendas_produto[2]}')

vendas totais de cada produto: [325 433 368]
vendas do produto 1: 325
vendas do produto 2: 433
vendas do produto 3: 368


In [16]:
#vendas diarias
vendas_diarias = vendas_totais.sum(axis=0)
print(f'Vendas diárias: {vendas_diarias}')

for i in range(5):
    print(f'vendas do dia {i+1}: {vendas_diarias[i]}')

#print(f'vendas do dia 1: {vendas_diarias[0]}')
#print(f'vendas do dia 2: {vendas_diarias[1]}')
#print(f'vendas do dia 3: {vendas_diarias[2]}')
#print(f'vendas do dia 4: {vendas_diarias[3]}')
#print(f'vendas do dia 5: {vendas_diarias[4]}')

Vendas diárias: [207 225 216 234 244]
vendas do dia 1: 207
vendas do dia 2: 225
vendas do dia 3: 216
vendas do dia 4: 234
vendas do dia 5: 244
