## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [12]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])

media = np.mean(salarios)
print(media)

3455.5555555555557


In [13]:
salarios_acima_media = np.where(salarios > media)
print(salarios_acima_media)

(array([2, 3, 5, 7, 8], dtype=int64),)


In [14]:
print(salarios[salarios_acima_media])


[3500 4000 4500 3800 4800]


In [20]:
print(True == 1)
print(False == 0)
#essas condiçoes sao do python, onde True = 1, que possibilita fazer a contagem dos salarios acima da media

True
True


In [19]:
print(salarios > media)
#isso printa se é True or False essa condição, e com isso podemos dar um np.sum que soma a quantidate de True,
#chegando na quantidade de salarios acima da media
funcionarios_acima_media = np.sum(salarios > media) 
print(f"{funcionarios_acima_media} ganham mais do que a media")

[False False  True  True False  True False  True  True]
5 ganham mais do que a media


## Bonus
## Outras formar de fazer contagem

In [21]:
print(np.count_nonzero(salarios > media)) #conta  o que nao for zero, ou seja, tudo que for True

5


In [22]:
print(np.unique(salarios > media)) #me diz quantos valores unicos existem

[False  True]


In [23]:
print(np.unique(salarios > media, return_counts=True)) ##me diz quantos valores unicos existem, e quantos existem deles

(array([False,  True]), array([4, 5], dtype=int64))


In [24]:
#por ser uma tupla, pode-se fazer o unpacking
valores_unicos, contagem = np.unique(salarios > media, return_counts=True)
print(valores_unicos)
print(contagem)


[False  True]
[4 5]


## Bonus 2
criando 20 valores ficticios de salarios com a mesma faixa anterior, tomando cuidado de outras pessoas gerarem o mesmos valores:

In [26]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20)
print(salarios_gerados)

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]


In [27]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20, endpoint=True)
print(salarios_gerados)

[2249 4167 3833 3229 3212 4404 2240 3953 2564 2263 3474 4732 4060 4131
 4009 4201 3437 2358 4352 3261]


In [28]:
print(np.mean(salarios_gerados))

3506.45


In [29]:
# as funcões estatisticas tambem podem ser chamadas como metodo de array

print(salarios_gerados.min())
print(salarios_gerados.max())
print(salarios_gerados.mean())


2240
4732
3506.45
